type DogmaAttribute {
  AttributeID: Int
	DefaultValue: Float
	Description: String
	DisplayName: String
	HighIsGood: Boolean
	IconID: Int
	Name: String
	Published: Boolean
	Stackable: Boolean
	UnitID: Int
}

type DogmaAttributeNode {
	AttributeID: Int
	Value: Float
	Attribute: DogmaAttribute
}
